version: '3.3'

services:
  nginx:
    container_name: nginx-con
    image: nginx:1.13.9-alpine
    volumes:
      - ./nginx/dev/:/etc/nginx/conf.d
    ports:
      - "80:80"
    restart: always
    depends_on:
      - client
  client:
    build:
      context: ./usersClient
      dockerfile: DockerFile
    container_name: client
    ports:
      - "4201:4200"
    command: ng serve --host 0.0.0.0 --disable-host-check
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./usersClient:/usr/src/app
    restart: always
    expose:
      - "4200"
  server:
    build:
      context: .
      dockerfile: javaDockerFile
    container_name: server
    ports:
      - "8080:8080"
    command: java -jar users-0.0.1-SNAPSHOT.jar
    restart: always
    environment:
      MYSQL_DB_HOST: 'db'
    expose:
      - "8080"     
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'tachles'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'   
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./config/my.cnf:/etc/mysql/my.cnf
      - my-db:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
# Names our volume
volumes:
  my-db: null
  
  

