FROM node:16.14.0
# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY . /usr/src/app
RUN npm install -g @angular/cli@12
RUN npm install 


EXPOSE 4200

# start app
# CMD ng serve --host 0.0.0.0